# Generated by Django 3.0.8 on 2020-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_job_doneornot'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_for_today',
            field=models.BooleanField(default=False),
        ),
    ]
